steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '--region=${_LOCATION}',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' 
    entrypoint: 'bash'
    args:
    - '-c'
    - > 
      gcloud deploy releases create release-$BUILD_ID --delivery-pipeline=hello-world-app --region=northamerica-northeast1 --source=./
      --images=hello-world-app=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA   
substitutions:
  _SERVICE_NAME: hello-world-service
  _LOCATION: northeast-northamerica1