---

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: sc-cloud-run-pipeline
description: sc cloud run application deployment pipeline
serialPipeline:
 stages:
 - targetId: dev-env
   profiles: [dev]
 - targetId: qa-env
   profiles: [qa]
 - targetId: perf-env
   profiles: [perf]  
 - targetId: uat-env
   profiles: [uat]  
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-env
description: Cloud Run development service
run:
 location: projects/sc-gcp-dev-367313/locations/northamerica-northeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qa-env
description: Cloud Run QA service
run:
 location: projects/sc-gcp-qa/locations/northamerica-northeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: perf-env
description: Cloud Run PERF service
run:
 location: projects/sc-gcp-perf/locations/northamerica-northeast1 
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: uat-env
description: Cloud Run UAT service
run:
 location: projects/sc-gcp-uat/locations/northamerica-northeast1  