---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: sc-cloud-run-pipeline
description: SC GCP application deployment pipeline
serialPipeline:
 stages:
 - targetId: dev-env
   profiles: [dev]
   
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-env
description: Cloud Run development service
run:
 location: projects/sc-gcp-dev-367313/locations/northamerica-northeast1
