apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
- name: qa
  manifests:
    rawYaml:
    - deploy-qa.yaml
- name: perf
  manifests:
    rawYaml:
    - deploy-perf.yaml
- name: uat
  manifests:
    rawYaml:
    - deploy-uat.yaml        
deploy:
  cloudrun: {}